[Settings]
;See https://codeberg.org/ltguillaume/chromium-winupdater#server-certificate-revocation
IgnoreCrlErrors=0
;Check for updates of Chromium WinUpdater first (use 0 to disable)
UpdateSelf=1

;Remove the semicolon in front of the 3 lines for the release you're using.
;This includes ReleaseApiUrl=, one InstallerFile= and one PortableFile=,
;depending on your Windows architecture (arm64, 64-bit/x64 or 32-bit/x86).
;Make no other ReleaseApiUrl=/InstallerFile=/PortableFile= line is uncommented.

;Ungoogled Chromium 64-bit - by Marmaduke (this is the default) - https://github.com/macchrome/winchrome
;ReleaseApiUrl=https://api.github.com/repos/macchrome/winchrome/releases/latest
;InstallerFile=*.exe
;PortableFile=*.7z

;Ungoogled Chromium - by Nifury et al. - https://github.com/ungoogled-software/ungoogled-chromium-windows
;ReleaseApiUrl=https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest
;InstallerFile=*arm64.exe
;PortableFile=*arm64.zip
;InstallerFile=*x64.exe
;PortableFile=*x64.zip
;InstallerFile=*x86.exe
;PortableFile=*x86.zip

;Cromite 64-bit by uazo - https://github.com/uazo/cromite
;ReleaseApiUrl=https://api.github.com/repos/uazo/cromite/releases/latest
;InstallerFile=NONE
;PortableFile=*win.zip

;Ungoogled Chromium AVX2 - by vpday - https://github.com/vpday/ungoogled-chromium-windows
;ReleaseApiUrl=https://api.github.com/repos/vpday/ungoogled-chromium-windows/releases/latest
;InstallerFile=*arm64.exe
;PortableFile=*arm64.zip
;InstallerFile=*x64.exe
;PortableFile=*x64.zip
;InstallerFile=*x86.exe
;PortableFile=*x86.zip

;Ungoogled Chromium 64-bit – by n1to9only - https://github.com/1to9only/ungoogled-chromium-windows-x64-binaries
;ReleaseApiUrl=https://api.github.com/repos/1to9only/ungoogled-chromium-windows-x64-binaries/releases/latest
;InstallerFile=*x64.exe
;PortableFile=*x64.zip
