[Settings]
;See https://codeberg.org/ltguillaume/chromium-winupdater#server-certificate-revocation
IgnoreCrlErrors=0
;Check for updates of Chromium WinUpdater first (use 0 to disable)
UpdateSelf=1

;Remove the semicolon in front of the 3 lines for the release you're using.
;This includes ReleaseApiUrl=, one InstallerFile= and one PortableFile=,
;depending on your Windows architecture (x64/64-bit, x86/32-bit/ia32 or arm64).
;Make sure all other ReleaseApiUrl=/InstallerFile=/PortableFile= lines are commented.

;Ungoogled Chromium official repository (this is the new default)
;By Nifury et al. - https://github.com/ungoogled-software/ungoogled-chromium-windows
;ReleaseApiUrl=https://api.github.com/repos/ungoogled-software/ungoogled-chromium-windows/releases/latest
;InstallerFile=*x64.exe
;PortableFile=*x64.zip
;InstallerFile=*x86.exe
;PortableFile=*x86.zip
;InstallerFile=*arm64.exe
;PortableFile=*arm64.zip

;Ungoogled Chromium x64, including Widevine (this was the default, but is now often outdated)
;By Marmaduke - https://github.com/macchrome/winchrome
;ReleaseApiUrl=https://api.github.com/repos/macchrome/winchrome/releases/latest
;InstallerFile=*.exe
;PortableFile=*.7z

;Brave portable, with ad blocking and additional privacy measures (https://privacytests.org)
;By Brave Software - https://github.com/brave/brave-browser
;Put Chromium-WinUpdater.exe next to Brave.exe
;Also contains metrics, a crypto wallet, AI, News, Talk and a VPN service
;To disable those, see https://codeberg.org/ltguillaume/chromium-winupdater/src/branch/brave
;ReleaseApiUrl=https://api.github.com/repos/brave/brave-browser/releases/latest
;InstallerFile=NONE
;PortableFile=*win32-x64.zip
;PortableFile=*win32-ia32.zip
;PortableFile=*win32-arm64.zip

;Cromite x64 with ad blocking and additional privacy patches, often behind
;By uazo - https://github.com/uazo/cromite
;ReleaseApiUrl=https://api.github.com/repos/uazo/cromite/releases/latest
;InstallerFile=NONE
;PortableFile=*win.zip

;Ungoogled Chromium x64 with builds usually several days earlier than the official repository, but lacks support
;By n1to9only - https://github.com/1to9only/ungoogled-chromium-windows-x64-binaries
;ReleaseApiUrl=https://api.github.com/repos/1to9only/ungoogled-chromium-windows-x64-binaries/releases/latest
;InstallerFile=*x64.exe
;PortableFile=*x64.zip

;Ungoogled Chromium AVX2 enabled, cross-compiled (on Ubuntu), somewhat behind
;By vpday - https://github.com/vpday/ungoogled-chromium-windows
;ReleaseApiUrl=https://api.github.com/repos/vpday/ungoogled-chromium-windows/releases/latest
;InstallerFile=*x64.exe
;PortableFile=*x64.zip
;InstallerFile=*x86.exe
;PortableFile=*x86.zip
;InstallerFile=*arm64.exe
;PortableFile=*arm64.zip

;Vanilla Chromium without field trials, with Widevine and Google Sync support
;By Hibbiki - https://github.com/Hibbiki/chromium-win64
;ReleaseApiUrl=https://api.github.com/repos/Hibbiki/chromium-win64/releases/latest
;InstallerFile=mini_installer.exe
;PortableFile=chrome.7z
